services:
  - type: web
    name: quiz-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    rootDir: backend
    envVars:
      - key: SESSION_SECRET
        value: your_secret_key
      - key: DATABASE_URL
        value: your_database_connection_string
      - key: FIREBASE_API_KEY
        value: your_firebase_key
      - key: FIREBASE_AUTH_DOMAIN
        value: your_project.firebaseapp.com
      - key: FIREBASE_PROJECT_ID
        value: your_project_id
